# Generated by Django 5.2 on 2025-05-08 04:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Fully Approved'), ('conditional', 'Conditionally Approved'), ('rejected', 'Rejected'), ('revoked', 'Approval Revoked')], default='pending', max_length=20)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('approval_id', models.CharField(max_length=50, unique=True)),
                ('approving_body', models.CharField(max_length=200)),
                ('risk_level', models.IntegerField(default=3, help_text='1=Lowest risk, 5=Highest risk', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Government Approvals',
            },
        ),
        migrations.CreateModel(
            name='EducationalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('duration', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educational_videos', to='base.governmentapproval')),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('product_type', models.CharField(choices=[('seed', 'Seeds'), ('crop', 'Crops'), ('processed', 'Processed Food'), ('animal', 'Animal Product')], max_length=20)),
                ('image', models.ImageField(upload_to='products/')),
                ('manufacturer', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('gmo_traits', models.TextField()),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.governmentapproval')),
            ],
        ),
    ]
