# Generated by Django 5.2 on 2025-05-08 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_governmentapproval_educationalvideo_verifiedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalvideo',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='educationalvideo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='educationalvideo',
            name='thumbnail',
            field=models.ImageField(help_text='Upload thumbnail image', null=True, upload_to='video_thumbnails/'),
        ),
        migrations.AddField(
            model_name='educationalvideo',
            name='video_file',
            field=models.FileField(help_text='Upload video file (MP4, MOV, AVI, MKV, or WEBM)', null=True, upload_to='educational_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='educationalvideo',
            name='duration',
            field=models.CharField(blank=True, help_text='Duration in format MM:SS (auto-calculated if blank)', max_length=10),
        ),
    ]
