# Generated by Django 5.2 on 2025-05-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_educationalvideo_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalvideo',
            name='thumbnail',
        ),
    ]
