# Generated by Django 5.2.1 on 2025-05-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_gmoproduct_qr_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalresource',
            name='url',
        ),
        migrations.AddField(
            model_name='educationalresource',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
